#ifndef CONFIG_H
#define CONFIG_H

#define IMG_W (188)
#define IMG_H (120)
#define IMG_CENTER (94)


#define DRIVE_LAUNCH_DELAY_S (2)
#define DRIVE_ARMED_TIMEOUT_S (30)
#define DRIVE_LAUNCH_DELAY_US ((uint32_t)DRIVE_LAUNCH_DELAY_S * 1000000u)


#define DRIVE_DT_CLAMP_US (200000u)
#define DRIVE_DT_NOMINAL_US (20000u)

#define FIXED_THRESHOLD (128)
#define OTSU_ROW_STEP (2)
#define OTSU_COL_STEP (2)
#define OTSU_THRESHOLD_MIN (40)
#define OTSU_THRESHOLD_MAX (200)


#define STEER_SPLIT_ROW  (45)
#define STEER_FAR_ROW_HI (90)
#define STEER_FAR_W_PCT  (65)


#define TRACK_HALF_W_FALLBACK (60)


#define ERR_HOLD_MAX_FRAMES (20)


#define TH18_COL_MARGIN          (20)
#define TH18_CROSS_BOTH_LOST_MIN (10)
#define IMG_FILTER_SUM_MAX (255 * 5)
#define IMG_FILTER_SUM_MIN (255 * 2)

#define SERVO_PWM_HZ (50)
#define SERVO_CENTER (705)
#define SERVO_MIN (629)
#define SERVO_MAX (781)
#define SERVO_DIR (-1)


#define KP (1.20f)
#define KD (1.49f)
#define D_FILT_ALPHA (0.4f)

#define STRAIGHT_DUTY (2100)
#define DUTY_HARD_CAP (6000)


#define DUTY_SLEW_UP (120)


#define FAILSAFE_MIN_ROWS (8)
#define FAILSAFE_MAX_BOTH_LOST_PCT (70)
#define FAILSAFE_SEVERE_BOTH_LOST_PCT (90)
#define FAILSAFE_FRAMES (10)
#define FAILSAFE_SEVERE_FRAMES (2)

#define MOTOR_PWM_FREQ (17000)

#define KEY_SCAN_PERIOD_MS (5)
#define KEY_DEBOUNCE_MS (20)
#define KEY_DEBOUNCE_COUNT (KEY_DEBOUNCE_MS / KEY_SCAN_PERIOD_MS)
#define KEY_LONG_PRESS_MS (1000)
#define KEY_REPEAT_MS (80)

#define MOTOR_TEST_DUTY (2000)


#define UART_TEST_PERIOD_US (200000u)


#define TELEM_DIV (5u)


#define PRESET_LOW_KP           (2.29f)
#define PRESET_LOW_KD         (1.49f)
#define PRESET_LOW_D_ALPHA    (0.40f)
#define PRESET_LOW_THRESHOLD  (0)
#define PRESET_LOW_CROSS_FILL (1)
#define PRESET_LOW_FAR_W      (STEER_FAR_W_PCT)
#define PRESET_LOW_DUTY       (2100)
#define PRESET_LOW_STOP_TIME  (105)


#define PRESET_MID_KP           (KP)
#define PRESET_MID_KD         (4.73f)
#define PRESET_MID_D_ALPHA    (0.40f)
#define PRESET_MID_THRESHOLD  (0)
#define PRESET_MID_CROSS_FILL (1)
#define PRESET_MID_FAR_W      (STEER_FAR_W_PCT)
#define PRESET_MID_DUTY       (3200)
#define PRESET_MID_STOP_TIME  (28)


#define PRESET_HIGH_KP           (KP)
#define PRESET_HIGH_KD         (KD)
#define PRESET_HIGH_D_ALPHA    (D_FILT_ALPHA)
#define PRESET_HIGH_THRESHOLD  (0)
#define PRESET_HIGH_CROSS_FILL (1)
#define PRESET_HIGH_FAR_W      (STEER_FAR_W_PCT)
#define PRESET_HIGH_DUTY       (STRAIGHT_DUTY)
#define PRESET_HIGH_STOP_TIME  (DRIVE_ARMED_TIMEOUT_S)

#endif
